import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { NextPage } from 'next';
import { AuthComponent } from '../components/auth';
import { Auth } from 'aws-amplify'
import { DynamoComponent } from '../components/aws/dynamodb';


const Home: NextPage = () => {
  const [user, setUser] = useState<any>()
  const [idToken, setIdToken] = useState<string>()

  useEffect(() => {
    const authCheck = async () => {
      const user = await Auth.currentAuthenticatedUser()
      setUser(user)

      const cognitoSession = await Auth.currentSession()
      const idToken = await cognitoSession.getIdToken()
      setIdToken(idToken.getJwtToken())
    }

    authCheck()
  }, []);

  return (
    <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Multi-tenant SaaS Stack
          </h1>

          <p className={styles.description}>
            Get started by signing up
          </p>
          {
             user && idToken ?
              <>
              <div>
                <p>Hello, {user.attributes.email}</p>
              </div>
                <DynamoComponent idToken={idToken} />
              </> :
              <AuthComponent/>
          }
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/simonireilly"
            target="_blank"
            rel="noopener noreferrer"
            >
            Created by Simon
          </a>
        </footer>
      </div>
  )
}

export default Home
